#!/bin/sh

source ./env

if [ -z $CONTAINER_ID ]; then
    echo "🔴 '$SERVICE_NAME' already stopped"
else
    echo "⚪️ Stop '$SERVICE_NAME'"

    if [ $SWARM_MODE == "active" ]; then
        docker service rm $SERVICE_NAME
    else
        docker stop $CONTAINER_ID
        docker rm  $CONTAINER_ID
    fi

    if [ $SWARM_MODE == "active" ]; then
        export CONTAINER_ID=$(docker ps -q -f "name=$SERVICE_NAME.1")
    else
        export CONTAINER_ID=$(docker ps -q -f "name=$SERVICE_NAME")
    fi

    if [ -z $CONTAINER_ID ]; then
        echo "🟢 '$SERVICE_NAME' stopped"
    else
        echo "🔴 '$SERVICE_NAME' did not stop"
    fi
fi